// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convolve_2d,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=2582,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=416,HLS_SYN_LUT=810,HLS_VERSION=2018_3}" *)

module convolve_2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_stream_V_din,
        out_stream_V_full_n,
        out_stream_V_write,
        in_stream_V_dout,
        in_stream_V_empty_n,
        in_stream_V_read,
        kernel_address0,
        kernel_ce0,
        kernel_q0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] out_stream_V_din;
input   out_stream_V_full_n;
output   out_stream_V_write;
input  [31:0] in_stream_V_dout;
input   in_stream_V_empty_n;
output   in_stream_V_read;
output  [3:0] kernel_address0;
output   kernel_ce0;
input  [31:0] kernel_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg out_stream_V_write;
reg in_stream_V_read;
reg kernel_ce0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_stream_V_blk_n;
wire    ap_CS_fsm_state13;
reg   [0:0] or_cond_reg_872;
wire   [0:0] exitcond1_i_fu_669_p2;
reg    in_stream_V_blk_n;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond7_fu_421_p2;
wire   [1:0] i_1_fu_353_p2;
reg   [1:0] i_1_reg_747;
wire    ap_CS_fsm_state2;
wire   [4:0] tmp_2_fu_371_p2;
reg   [4:0] tmp_2_reg_752;
wire   [0:0] exitcond1_fu_347_p2;
wire   [2:0] j_1_fu_383_p2;
wire    ap_CS_fsm_state3;
wire   [2:0] y_fu_409_p2;
reg   [2:0] y_reg_768;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_1_fu_415_p2;
reg   [0:0] tmp_1_reg_773;
wire   [0:0] exitcond8_fu_403_p2;
wire   [2:0] x_fu_427_p2;
reg   [2:0] x_reg_781;
reg    ap_block_state5;
reg   [31:0] tmp_28_reg_786;
wire   [1:0] i_3_fu_439_p2;
reg   [1:0] i_3_reg_795;
wire    ap_CS_fsm_state6;
wire   [4:0] tmp_5_fu_461_p2;
reg   [4:0] tmp_5_reg_800;
wire   [0:0] exitcond6_fu_433_p2;
wire   [4:0] tmp_8_cast_fu_467_p1;
reg   [4:0] tmp_8_cast_reg_806;
wire   [1:0] j_2_fu_477_p2;
reg   [1:0] j_2_reg_816;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond5_fu_471_p2;
wire   [4:0] tmp_18_fu_501_p2;
reg   [4:0] tmp_18_reg_826;
wire   [1:0] i_2_fu_516_p2;
reg   [1:0] i_2_reg_834;
wire    ap_CS_fsm_state9;
wire   [0:0] exitcond4_fu_510_p2;
wire   [4:0] tmp_16_fu_568_p2;
reg   [4:0] tmp_16_reg_844;
wire   [1:0] i_4_fu_584_p2;
reg   [1:0] i_4_reg_852;
wire    ap_CS_fsm_state11;
wire   [0:0] tmp_10_fu_590_p2;
reg   [0:0] tmp_10_reg_857;
wire   [0:0] exitcond_fu_578_p2;
wire   [4:0] tmp_24_fu_642_p2;
reg   [4:0] tmp_24_reg_867;
wire   [0:0] or_cond_fu_653_p2;
wire   [1:0] i_5_fu_675_p2;
reg   [1:0] i_5_reg_879;
reg    ap_predicate_op165_write_state13;
reg    ap_block_state13;
wire   [4:0] tmp_26_fu_697_p2;
reg   [4:0] tmp_26_reg_884;
wire   [1:0] j_3_fu_709_p2;
reg   [1:0] j_3_reg_892;
wire    ap_CS_fsm_state14;
wire   [0:0] exitcond_i_fu_703_p2;
wire   [31:0] window_q0;
reg  signed [31:0] window_load_1_reg_907;
wire    ap_CS_fsm_state15;
reg  signed [31:0] kernel_load_reg_912;
wire   [31:0] tmp_17_i_fu_730_p2;
reg   [31:0] tmp_17_i_reg_917;
wire    ap_CS_fsm_state16;
wire   [31:0] result_fu_734_p2;
wire    ap_CS_fsm_state17;
reg   [3:0] line_buf_address0;
reg    line_buf_ce0;
reg    line_buf_we0;
reg   [31:0] line_buf_d0;
wire   [31:0] line_buf_q0;
reg   [3:0] window_address0;
reg    window_ce0;
reg    window_we0;
reg   [31:0] window_d0;
reg   [1:0] i_reg_211;
wire   [0:0] exitcond9_fu_377_p2;
reg   [2:0] j_reg_222;
reg   [2:0] y_assign_reg_233;
reg   [2:0] x_assign_reg_244;
reg   [1:0] i1_reg_256;
reg   [1:0] j2_reg_267;
wire    ap_CS_fsm_state8;
reg   [1:0] i3_reg_278;
wire    ap_CS_fsm_state10;
reg   [1:0] i4_reg_289;
wire    ap_CS_fsm_state12;
reg   [31:0] result_2_reg_300;
reg   [1:0] i_i_reg_313;
reg   [31:0] result_1_i_reg_324;
reg   [1:0] j_i_reg_336;
wire  signed [63:0] tmp_18_cast_fu_398_p1;
wire  signed [63:0] tmp_27_cast_fu_492_p1;
wire  signed [63:0] tmp_28_cast_fu_506_p1;
wire  signed [63:0] tmp_23_cast_fu_545_p1;
wire  signed [63:0] tmp_26_cast_fu_574_p1;
wire  signed [63:0] tmp_31_cast_fu_619_p1;
wire  signed [63:0] tmp_34_cast_fu_665_p1;
wire  signed [63:0] tmp_38_cast_fu_724_p1;
wire   [31:0] tmp_15_fu_658_p3;
wire   [4:0] tmp_s_fu_363_p3;
wire   [4:0] tmp_cast_fu_359_p1;
wire   [4:0] tmp_3_cast_fu_389_p1;
wire   [4:0] tmp_3_fu_393_p2;
wire   [3:0] tmp_4_fu_449_p3;
wire   [4:0] p_shl1_cast_fu_457_p1;
wire   [4:0] tmp_9_cast_fu_445_p1;
wire   [4:0] tmp_4_cast_fu_483_p1;
wire   [4:0] tmp_17_fu_487_p2;
wire   [4:0] tmp_5_cast_fu_497_p1;
wire   [4:0] tmp_8_fu_526_p3;
wire   [4:0] tmp_cast_13_fu_522_p1;
wire   [4:0] tmp_9_fu_534_p2;
wire   [4:0] tmp_11_fu_540_p2;
wire   [3:0] tmp_13_fu_550_p3;
wire   [4:0] p_shl2_cast_fu_558_p1;
wire   [4:0] tmp_14_fu_562_p2;
wire   [4:0] tmp_19_fu_600_p3;
wire   [4:0] tmp_14_cast_fu_596_p1;
wire   [4:0] tmp_20_fu_608_p2;
wire   [4:0] tmp_21_fu_614_p2;
wire   [4:0] tmp_22_fu_628_p3;
wire   [4:0] tmp_16_cast_fu_624_p1;
wire   [4:0] tmp_23_fu_636_p2;
wire   [0:0] tmp_7_fu_647_p2;
wire   [3:0] tmp_25_fu_685_p3;
wire   [4:0] p_shl6_cast_fu_693_p1;
wire   [4:0] tmp_i1_cast_fu_681_p1;
wire   [4:0] tmp_i2_cast_fu_715_p1;
wire   [4:0] tmp_27_fu_719_p2;
reg   [16:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

convolve_2d_line_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 14 ),
    .AddressWidth( 4 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_address0),
    .ce0(line_buf_ce0),
    .we0(line_buf_we0),
    .d0(line_buf_d0),
    .q0(line_buf_q0)
);

convolve_2d_window #(
    .DataWidth( 32 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
window_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(window_address0),
    .ce0(window_ce0),
    .we0(window_we0),
    .d0(window_d0),
    .q0(window_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_471_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        i1_reg_256 <= i_3_reg_795;
    end else if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        i1_reg_256 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond6_fu_433_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i3_reg_278 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        i3_reg_278 <= i_2_reg_834;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i4_reg_289 <= i_4_reg_852;
    end else if (((exitcond4_fu_510_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        i4_reg_289 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_653_p2 == 1'd1) & (exitcond_fu_578_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        i_i_reg_313 <= 2'd0;
    end else if (((exitcond_i_fu_703_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        i_i_reg_313 <= i_5_reg_879;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond9_fu_377_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_reg_211 <= i_1_reg_747;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_211 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond6_fu_433_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        j2_reg_267 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        j2_reg_267 <= j_2_reg_816;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        j_i_reg_336 <= j_3_reg_892;
    end else if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (exitcond1_i_fu_669_p2 == 1'd0) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        j_i_reg_336 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_222 <= 3'd0;
    end else if (((exitcond9_fu_377_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_reg_222 <= j_1_fu_383_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        result_1_i_reg_324 <= result_fu_734_p2;
    end else if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (exitcond1_i_fu_669_p2 == 1'd0) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        result_1_i_reg_324 <= result_2_reg_300;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_fu_653_p2 == 1'd1) & (exitcond_fu_578_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        result_2_reg_300 <= 32'd0;
    end else if (((exitcond_i_fu_703_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        result_2_reg_300 <= result_1_i_reg_324;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond8_fu_403_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        x_assign_reg_244 <= 3'd0;
    end else if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13) & ((exitcond1_i_fu_669_p2 == 1'd1) | (or_cond_reg_872 == 1'd0)))) begin
        x_assign_reg_244 <= x_reg_781;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_347_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        y_assign_reg_233 <= 3'd0;
    end else if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        y_assign_reg_233 <= y_reg_768;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_747 <= i_1_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_2_reg_834 <= i_2_fu_516_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i_3_reg_795 <= i_3_fu_439_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        i_4_reg_852 <= i_4_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        i_5_reg_879 <= i_5_fu_675_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        j_2_reg_816 <= j_2_fu_477_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_3_reg_892 <= j_3_fu_709_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        kernel_load_reg_912 <= kernel_q0;
        window_load_1_reg_907 <= window_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_578_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        or_cond_reg_872 <= or_cond_fu_653_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_578_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        tmp_10_reg_857 <= tmp_10_fu_590_p2;
        tmp_24_reg_867 <= tmp_24_fu_642_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_510_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        tmp_16_reg_844 <= tmp_16_fu_568_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        tmp_17_i_reg_917 <= tmp_17_i_fu_730_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_471_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        tmp_18_reg_826 <= tmp_18_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond8_fu_403_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_1_reg_773 <= tmp_1_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (exitcond1_i_fu_669_p2 == 1'd0) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        tmp_26_reg_884 <= tmp_26_fu_697_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_28_reg_786 <= in_stream_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_347_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_2_reg_752 <= tmp_2_fu_371_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond6_fu_433_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_5_reg_800 <= tmp_5_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond6_fu_433_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_8_cast_reg_806[2 : 0] <= tmp_8_cast_fu_467_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state5))) begin
        x_reg_781 <= x_fu_427_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_reg_768 <= y_fu_409_p2;
    end
end

always @ (*) begin
    if (((exitcond8_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond8_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond7_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        in_stream_V_blk_n = in_stream_V_empty_n;
    end else begin
        in_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        in_stream_V_read = 1'b1;
    end else begin
        in_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        line_buf_address0 = tmp_34_cast_fu_665_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        line_buf_address0 = tmp_31_cast_fu_619_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buf_address0 = tmp_23_cast_fu_545_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buf_address0 = tmp_18_cast_fu_398_p1;
    end else begin
        line_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9))) begin
        line_buf_ce0 = 1'b1;
    end else begin
        line_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        line_buf_d0 = tmp_15_fu_658_p3;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        line_buf_d0 = 32'd0;
    end else begin
        line_buf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((exitcond9_fu_377_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        line_buf_we0 = 1'b1;
    end else begin
        line_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_fu_669_p2 == 1'd1) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_V_blk_n = out_stream_V_full_n;
    end else begin
        out_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (ap_predicate_op165_write_state13 == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        out_stream_V_write = 1'b1;
    end else begin
        out_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        window_address0 = tmp_38_cast_fu_724_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        window_address0 = tmp_26_cast_fu_574_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        window_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        window_address0 = tmp_28_cast_fu_506_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        window_address0 = tmp_27_cast_fu_492_p1;
    end else begin
        window_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7))) begin
        window_ce0 = 1'b1;
    end else begin
        window_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        window_d0 = line_buf_q0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        window_d0 = tmp_28_reg_786;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        window_d0 = window_q0;
    end else begin
        window_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8) | ((exitcond4_fu_510_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)))) begin
        window_we0 = 1'b1;
    end else begin
        window_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_347_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond9_fu_377_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond8_fu_403_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0)) & (exitcond7_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((exitcond6_fu_433_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((exitcond5_fu_471_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            if (((exitcond4_fu_510_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            if (((exitcond_fu_578_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state13 : begin
            if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state13) & ((exitcond1_i_fu_669_p2 == 1'd1) | (or_cond_reg_872 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0)) & (exitcond1_i_fu_669_p2 == 1'd0) & (or_cond_reg_872 == 1'd1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((exitcond_i_fu_703_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state13 = ((ap_predicate_op165_write_state13 == 1'b1) & (out_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state5 = ((exitcond7_fu_421_p2 == 1'd0) & (in_stream_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_predicate_op165_write_state13 = ((exitcond1_i_fu_669_p2 == 1'd1) & (or_cond_reg_872 == 1'd1));
end

assign exitcond1_fu_347_p2 = ((i_reg_211 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond1_i_fu_669_p2 = ((i_i_reg_313 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond4_fu_510_p2 = ((i3_reg_278 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond5_fu_471_p2 = ((j2_reg_267 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond6_fu_433_p2 = ((i1_reg_256 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond7_fu_421_p2 = ((x_assign_reg_244 == 3'd7) ? 1'b1 : 1'b0);

assign exitcond8_fu_403_p2 = ((y_assign_reg_233 == 3'd7) ? 1'b1 : 1'b0);

assign exitcond9_fu_377_p2 = ((j_reg_222 == 3'd7) ? 1'b1 : 1'b0);

assign exitcond_fu_578_p2 = ((i4_reg_289 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond_i_fu_703_p2 = ((j_i_reg_336 == 2'd3) ? 1'b1 : 1'b0);

assign i_1_fu_353_p2 = (i_reg_211 + 2'd1);

assign i_2_fu_516_p2 = (i3_reg_278 + 2'd1);

assign i_3_fu_439_p2 = (i1_reg_256 + 2'd1);

assign i_4_fu_584_p2 = (i4_reg_289 + 2'd1);

assign i_5_fu_675_p2 = (i_i_reg_313 + 2'd1);

assign j_1_fu_383_p2 = (j_reg_222 + 3'd1);

assign j_2_fu_477_p2 = (j2_reg_267 + 2'd1);

assign j_3_fu_709_p2 = (j_i_reg_336 + 2'd1);

assign kernel_address0 = tmp_38_cast_fu_724_p1;

assign or_cond_fu_653_p2 = (tmp_7_fu_647_p2 & tmp_1_reg_773);

assign out_stream_V_din = result_2_reg_300;

assign p_shl1_cast_fu_457_p1 = tmp_4_fu_449_p3;

assign p_shl2_cast_fu_558_p1 = tmp_13_fu_550_p3;

assign p_shl6_cast_fu_693_p1 = tmp_25_fu_685_p3;

assign result_fu_734_p2 = (result_1_i_reg_324 + tmp_17_i_reg_917);

assign tmp_10_fu_590_p2 = ((i4_reg_289 == 2'd1) ? 1'b1 : 1'b0);

assign tmp_11_fu_540_p2 = (tmp_9_fu_534_p2 + tmp_8_cast_reg_806);

assign tmp_13_fu_550_p3 = {{i3_reg_278}, {2'd0}};

assign tmp_14_cast_fu_596_p1 = i_4_fu_584_p2;

assign tmp_14_fu_562_p2 = (p_shl2_cast_fu_558_p1 - tmp_cast_13_fu_522_p1);

assign tmp_15_fu_658_p3 = ((tmp_10_reg_857[0:0] === 1'b1) ? tmp_28_reg_786 : line_buf_q0);

assign tmp_16_cast_fu_624_p1 = i4_reg_289;

assign tmp_16_fu_568_p2 = (tmp_14_fu_562_p2 + 5'd2);

assign tmp_17_fu_487_p2 = (tmp_5_reg_800 + tmp_4_cast_fu_483_p1);

assign tmp_17_i_fu_730_p2 = ($signed(kernel_load_reg_912) * $signed(window_load_1_reg_907));

assign tmp_18_cast_fu_398_p1 = $signed(tmp_3_fu_393_p2);

assign tmp_18_fu_501_p2 = (tmp_5_reg_800 + tmp_5_cast_fu_497_p1);

assign tmp_19_fu_600_p3 = {{i_4_fu_584_p2}, {3'd0}};

assign tmp_1_fu_415_p2 = ((y_assign_reg_233 != 3'd0) ? 1'b1 : 1'b0);

assign tmp_20_fu_608_p2 = (tmp_19_fu_600_p3 - tmp_14_cast_fu_596_p1);

assign tmp_21_fu_614_p2 = (tmp_20_fu_608_p2 + tmp_8_cast_reg_806);

assign tmp_22_fu_628_p3 = {{i4_reg_289}, {3'd0}};

assign tmp_23_cast_fu_545_p1 = $signed(tmp_11_fu_540_p2);

assign tmp_23_fu_636_p2 = (tmp_22_fu_628_p3 - tmp_16_cast_fu_624_p1);

assign tmp_24_fu_642_p2 = (tmp_23_fu_636_p2 + tmp_8_cast_reg_806);

assign tmp_25_fu_685_p3 = {{i_i_reg_313}, {2'd0}};

assign tmp_26_cast_fu_574_p1 = $signed(tmp_16_reg_844);

assign tmp_26_fu_697_p2 = (p_shl6_cast_fu_693_p1 - tmp_i1_cast_fu_681_p1);

assign tmp_27_cast_fu_492_p1 = $signed(tmp_17_fu_487_p2);

assign tmp_27_fu_719_p2 = (tmp_26_reg_884 + tmp_i2_cast_fu_715_p1);

assign tmp_28_cast_fu_506_p1 = $signed(tmp_18_reg_826);

assign tmp_2_fu_371_p2 = (tmp_s_fu_363_p3 - tmp_cast_fu_359_p1);

assign tmp_31_cast_fu_619_p1 = $signed(tmp_21_fu_614_p2);

assign tmp_34_cast_fu_665_p1 = $signed(tmp_24_reg_867);

assign tmp_38_cast_fu_724_p1 = $signed(tmp_27_fu_719_p2);

assign tmp_3_cast_fu_389_p1 = j_reg_222;

assign tmp_3_fu_393_p2 = (tmp_2_reg_752 + tmp_3_cast_fu_389_p1);

assign tmp_4_cast_fu_483_p1 = j_2_fu_477_p2;

assign tmp_4_fu_449_p3 = {{i1_reg_256}, {2'd0}};

assign tmp_5_cast_fu_497_p1 = j2_reg_267;

assign tmp_5_fu_461_p2 = (p_shl1_cast_fu_457_p1 - tmp_9_cast_fu_445_p1);

assign tmp_7_fu_647_p2 = ((x_assign_reg_244 != 3'd0) ? 1'b1 : 1'b0);

assign tmp_8_cast_fu_467_p1 = x_assign_reg_244;

assign tmp_8_fu_526_p3 = {{i3_reg_278}, {3'd0}};

assign tmp_9_cast_fu_445_p1 = i1_reg_256;

assign tmp_9_fu_534_p2 = (tmp_8_fu_526_p3 - tmp_cast_13_fu_522_p1);

assign tmp_cast_13_fu_522_p1 = i3_reg_278;

assign tmp_cast_fu_359_p1 = i_reg_211;

assign tmp_i1_cast_fu_681_p1 = i_i_reg_313;

assign tmp_i2_cast_fu_715_p1 = j_i_reg_336;

assign tmp_s_fu_363_p3 = {{i_reg_211}, {3'd0}};

assign x_fu_427_p2 = (x_assign_reg_244 + 3'd1);

assign y_fu_409_p2 = (y_assign_reg_233 + 3'd1);

always @ (posedge ap_clk) begin
    tmp_8_cast_reg_806[4:3] <= 2'b00;
end

endmodule //convolve_2d
